### ISSUE TITLE
[BUG] - Build script is gevoelig aan quotes type

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-util#118]
**Omschrijf het probleem**
Bij vl-ui-grid v3.0.0 was de import in de (src.js) build niet goed vervangen.

**Hoe te reproduceren**
NPM script uitvoeren om te builden en zien dat de import in de src gebruik maakt van dubbele quotes:

```JavaScript
import {NativeVlElement, define} from "/node_modules/vl-ui-core/dist/vl-core.js";
```

Indien er enkele quotes gebruikt worden, wordt de (src.js) build wel correct uitgevoerd.

```JavaScript
import {NativeVlElement, define} from '/node_modules/vl-ui-core/dist/vl-core.js';
```

**Gewenst gedrag**
Dubbele quotes ondersteuning toevoegen.

**Comment by coemans** [comment]
@kevcraey misschien best niet te lang wachten met dit issue. Is gerelateerd aan CommonJS update en zal potentieel in de toekomst voor problemen zorgen. De fix zou eenvoudig moeten zijn.

**Comment by kevcraey** [comment]
zal ik oppikken zodra we huidige WIP weggewerkt hebben.

**Comment by coemans** [comment]
Probleem is al opgelost in release [v5.0.0](https://github.com/milieuinfo/webcomponent-vl-ui-util/releases/tag/v5.0.0).
