### ISSUE TITLE
[TASK] - wacht op selenium grid voor het uitvoeren van de testen

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-ui-util#119]
**Beschrijving**
Momenteel doet zich het probleem niet voor omdat we bij het uitvoeren van de testen eerst alle source en node_modules kopiëren in de docker container, wat eventjes duurt. Echter, als dat ooit zou veranderen moeten we een script voorzien dat voor het uitvoeren van de testen wacht op de beschikbaarheid van de Selenium Grid en de nodes.

Onderstaande is al een begin:

```
#!/bin/bash

set -e

maxDelay=30

while [[ $maxDelay -gt 0 ]]
do
  if curl -sSL "http://selenium-hub:4444/wd/hub/status" 2>&1 | grep "Hub has capacity" >/dev/null
  then
    echo "Selenium Grid is up"
    exit 0
  else
    echo "Waiting for Selenium Grid"
    sleep 1
    maxDelay=$((maxDelay - 1))
  fi
done

echo "Timed out while waiting for Selenium Grid"
exit 1
```

**Comment by coemans** [comment]
Niet meer van toepassing aangezien we nu de testen draaien via Browserstack.
