### ISSUE TITLE
[BUG] - Probleem met instanceof

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-util#257]
**Omschrijf het probleem**
ES6 laat toe om het type van een object te weten, via bvb instanceof of object.constructor.name. Momenteel wordt dit geminified waardoor je niet kunt nagaan welk object je vast hebt. 

Als we dus nu default de interacties van openlayers itereren die we krijgen via de vl-map zien we het volgende gedrag:

```
import {DragPan} from "ol/interaction";

 olMap.getInteractions().forEach(interaction => {
      console.log(`First DragPan ${interaction instanceof DragPan}`);
      if (interaction) {
        console.log(interaction.constructor.name);
      }
      olMap.removeInteraction(interaction);
    });
    olMap.addInteraction(new DragPan());
    olMap.getInteractions().forEach(interaction => {
      console.log(`Second DragPan ${interaction instanceof DragPan}`);
      if (interaction) {
        console.log(interaction.constructor.name);
      }
    });
```

Bij de eerste loop vind je geen enkele interactie die en DragPan is, cfr alles is false. De namen zijn ook minified. Ik vermoed dat de interacties die hier toegevoegd worden van een minified openlayers source komen.

Bij de tweede loop zie je 1 interactie die true zegt, nl die van de DragPan en zie je ook de juiste naam tevoorschijn komen. Van belang voor de tweede loop, is dat we de DragPan importeren uit de openlayers source die niet minified is. 

Op zich zou in beide gevallen instanceof moeten werken.

**Comment by coemans** [comment]
Probleem lijkt me zeer OpenLayers specifiek. Ik denk dat dit best in kader van vl-mapactions bekeken wordt: [#46](https://github.com/milieuinfo/vl-mapactions/issues/46).
